/*
 * CyclicFrame.java
 *
 * Created on 25 de marzo de 2008, 10:35 PM
 */

package ruletest;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class CyclicFrame extends javax.swing.JInternalFrame {
    String TipoV, NumR, Motor, vehiculo,puetras,tam;
    BaseReglas objBS=new BaseReglas();
    /** Creates new form CyclicFrame */
    public CyclicFrame(String tipov) {
        TipoV=tipov;
        initComponents();
        jLTV.setText(TipoV);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLTV = new javax.swing.JLabel();
        jCBNumR = new javax.swing.JComboBox();
        jRBMotorSi = new javax.swing.JRadioButton();
        jRBMotorNo = new javax.swing.JRadioButton();
        jBSend = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Vehiculo Cyclic");

        jLabel1.setText("Tipo de Vehiculo:");

        jLabel2.setText("Numero de Ruedas:");

        jLabel3.setText("Motor:");

        jLTV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTV.setForeground(new java.awt.Color(0, 0, 102));
        jLTV.setText("jLabel4");

        jCBNumR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));

        jRBMotorSi.setText("Si");
        jRBMotorSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMotorSiActionPerformed(evt);
            }
        });

        jRBMotorNo.setText("No");
        jRBMotorNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMotorNoActionPerformed(evt);
            }
        });

        jBSend.setText("Enviar");
        jBSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSendActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBMotorSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBMotorNo))
                            .addComponent(jCBNumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTV)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBSend)
                        .addGap(27, 27, 27)
                        .addComponent(jBCancel)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLTV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBNumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBMotorNo)
                        .addComponent(jRBMotorSi)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSend)
                    .addComponent(jBCancel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                    
    private void jRBMotorSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMotorSiActionPerformed
        // TODO add your handling code here:
       if (jRBMotorSi.isSelected())
        {
            jRBMotorNo.setSelected(false);
            Motor = "yes";
        }
}//GEN-LAST:event_jRBMotorSiActionPerformed

    private void jBSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSendActionPerformed
      
}//GEN-LAST:event_jBSendActionPerformed

    private void jRBMotorNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMotorNoActionPerformed
        // TODO add your handling code here:
         if (jRBMotorNo.isSelected())
        {
            jRBMotorSi.setSelected(false);
            Motor = "no";
        }
    }//GEN-LAST:event_jRBMotorNoActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSend;
    private javax.swing.JComboBox jCBNumR;
    private javax.swing.JLabel jLTV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBMotorNo;
    private javax.swing.JRadioButton jRBMotorSi;
    // End of variables declaration//GEN-END:variables
    
}
