/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ruletest;

import java.sql.*;

/**
 *
 * @author Christian
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    
    public Resultados() {
        initComponents();
    }
    
    Principal objP;
    //TipoVFrame vFrame = new TipoVFrame(objP);
    TipoVFrame vFrame;
    ConexionSQL Conexion = new ConexionSQL();
    
    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null; 
    
    public String modelo = "";
    
    public void setModelo(String _modelo){modelo = _modelo;}
    public String getModelo(){return modelo;}
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBMP3 = new javax.swing.JCheckBox();
        jCBMSD = new javax.swing.JCheckBox();
        jCBB = new javax.swing.JCheckBox();
        jCBWifi = new javax.swing.JCheckBox();
        jCBMMS = new javax.swing.JCheckBox();
        jCBAndroid = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCBWin = new javax.swing.JCheckBox();
        jCBIos = new javax.swing.JCheckBox();
        jLMarca = new javax.swing.JLabel();
        jLModelo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCBSMS = new javax.swing.JCheckBox();
        jCBPropio = new javax.swing.JCheckBox();
        jCBCamara = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Modelo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tecnologías");

        jCBMP3.setText("MP3");

        jCBMSD.setText("Micro SD incluida");

        jCBB.setText("Bluetooth");

        jCBWifi.setText("Wi-fi");

        jCBMMS.setText("Mensajes multimedia (MMS)");

        jCBAndroid.setText("Android");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sistemas operativos");

        jCBWin.setText("Windows Phone");

        jCBIos.setText("iOS");

        jLMarca.setText("$marca");

        jLModelo.setText("$modelo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Los datos del equipo recomendado son los siguientes:");

        jCBSMS.setText("Mensajes de texto (SMS)");

        jCBPropio.setText("Propio/Otro");

        jCBCamara.setText("Camara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLModelo))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBAndroid)
                        .addGap(16, 16, 16)
                        .addComponent(jCBWin)
                        .addGap(18, 18, 18)
                        .addComponent(jCBIos)
                        .addGap(18, 18, 18)
                        .addComponent(jCBPropio))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBMSD)
                            .addComponent(jCBMP3)
                            .addComponent(jCBB)
                            .addComponent(jCBWifi))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBMMS)
                            .addComponent(jCBSMS)
                            .addComponent(jCBCamara))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLModelo))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMP3)
                    .addComponent(jCBSMS))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMSD)
                    .addComponent(jCBMMS))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jCBB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBWifi)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCamara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAndroid)
                    .addComponent(jCBWin)
                    .addComponent(jCBIos)
                    .addComponent(jCBPropio))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setResizable(false);
        
        System.out.println("vFrame.getPhone() --->"+getModelo());
        
        try {
            conn=Conexion.Enlace(conn);
            //rs = Conexion.getAllFeatures(st, vFrame.tipoV);
            rs = Conexion.getAllFeatures(st, "IPHONE 4S 64GB");
            while (rs.next()) {
                //jLMarca.setText(vFrame.tipoV);                
                jLMarca.setText(rs.getString("marca"));
                jLModelo.setText(rs.getString("modelo"));
           // caracteristicas
                if (rs.getInt("mp3") == 1) 
                    jCBMP3.setSelected(true);
                
                if (rs.getInt("SD") == 1)
                    jCBMSD.setSelected(true);
                if (rs.getInt("camara")== 1)
                    jCBCamara.setSelected(true);
                if (rs.getInt("bluetooth")== 1)
                    jCBB.setSelected(true);
                if (rs.getInt("wifi")== 1)
                    jCBWifi.setSelected(true);
                if (rs.getInt("mms")== 1)
                    jCBMMS.setSelected(true);
                if (rs.getInt("sms")== 1)
                    jCBSMS.setSelected(true);
                
           //sistemas operativos           
                if (rs.getInt("android")== 1)
                    jCBAndroid.setSelected(true);
                if (rs.getInt("ios")== 1)
                    jCBIos.setSelected(true);
                if (rs.getInt("windows_phone")== 1)
                    jCBWin.setSelected(true);
                if (rs.getInt("windows_phone")== 1 && 
                        rs.getInt("android")== 1 &&
                        rs.getInt("ios")== 1)
                    jCBPropio.setSelected(true);
            }
        } catch(SQLException e){
    
        }        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCBAndroid;
    private javax.swing.JCheckBox jCBB;
    private javax.swing.JCheckBox jCBCamara;
    private javax.swing.JCheckBox jCBIos;
    private javax.swing.JCheckBox jCBMMS;
    private javax.swing.JCheckBox jCBMP3;
    private javax.swing.JCheckBox jCBMSD;
    private javax.swing.JCheckBox jCBPropio;
    private javax.swing.JCheckBox jCBSMS;
    private javax.swing.JCheckBox jCBWifi;
    private javax.swing.JCheckBox jCBWin;
    private javax.swing.JLabel jLMarca;
    private javax.swing.JLabel jLModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
